apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h0hzkfl0l-python
  janus-idp.io/tekton: h0hzkfl0l-python
  backstage.io/kubernetes-id: h0hzkfl0l-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h0hzkfl0l-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
